### ISSUE TITLE
[BUG] Typings Error

### ISSUE THREAD

**Issue by ghost** [bsian03/pluris#7]
**Describe the bug**
There's a typings error that the TypeScript transpiler shows when transpiling my project. It's something to do with a constraint.
```ts
node_modules/eris/index.d.ts:2222:16 - error TS2428: All declarations of 'Message' must have identical type parameters.

2222   export class Message<T extends PossiblyUncachedTextable = TextableChannel> extends Base {
                    ~~~~~~~

node_modules/pluris/index.d.ts:111:13 - error TS2428: All declarations of 'Message' must have identical type parameters.       

111   interface Message<T extends Textable = TextableChannel> {
                ~~~~~~~

node_modules/pluris/index.d.ts:112:82 - error TS2344: Type 'T' does not satisfy the constraint 'Textable'.
  Type 'PossiblyUncachedTextable' is not assignable to type 'Textable'.
    Type 'Uncached' is missing the following properties from type 'Textable': lastMessageID, messages, addMessageReaction, createMessage, and 12 more.

112     awaitReactions(options: ReactionCollectorOptions): Promise<ReactionCollector<T>>;
                                                                                     ~
```

**Example code to reproduce**
```js
// No code is needed.
```

**Expected behavior**
There shouldn't be a typings error when transpiling.

**Environment**
| Node version | Eris version | Pluris version |
|--------------|--------------|----------------|
| v15.13.0     | 0.15.1       | 0.3.5          |

**Additional context**
- [ ] I know exactly what the issue is and will create a PR to fix it.
- [x] I do not know how to fix the bug/issue or I am only reporting the bug and will not create a PR.

**Comment by bsian03** [comment]
This is because pluris currently supports Eris 0.14.x for typescript due to a breaking change (typings) in 0.15.x. For now, try disabling `skipLibCheck`

**Comment by ghost** [comment]
Understandable. Should I close this issue now or leave it open until the typings are updated?

**Comment by bsian03** [comment]
`npm i bsian03/pluris`, full release will be coming later
